openapi: '3.0.2'
info:
  title: RFIDLobby
  version: '1.0'
servers:
  - url: http://localhost:8080
  - url: https://qr-lobby.haveachin.de

# ENDPOINTS ####################################################################

paths:
  /useraccounts:
    post:
      tags:
        - UserAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostUserAccount"
      responses:
        '201':
          description: Created.
        '400':
          description: Bad Request.
        '500':
          description: Internal Server Error.

  /useraccounts/{username}/availability:
    get:
      tags:
        - UserAccount
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
            description: Username to check availability
            example: JohnDoe
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '400':
          description: Bad Request.
        '500':
          description: Internal Server Error.

# SCHEMAS ######################################################################

components:
  schemas:
    ID:
      type: integer
      example: 1

    PostUserAccount:
      type: object
      required:
        - username
        - password
        - name
      properties:
        username:
          type: string
          example: JohnDoe
        password:
          type: string
          example: passwordExample
        name:
          type: string
          example: John Doe

# PARAMETERS ###################################################################

  parameters:
    UserAccountID:
      name: userAccountID
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/ID"
