name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chopper: ^7.1.1+1
  crypton: ^2.2.1
  pointycastle: ^3.7.4

  #Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  jwt_decoder: ^2.0.1

  #Page Transitions
  page_transition: ^2.1.0
  intl: ^0.19.0

  #State Management
  flutter_bloc: ^8.0.8

  image_picker: ^1.0.7

  #Displaying and scanning QR-Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner:
  chopper_generator: 

  #Local Storage
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
