name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chopper: 
  crypton: ^2.2.1
  pointycastle: ^3.7.4

  #Local Storage
  hive: 
  hive_flutter:
  jwt_decoder: ^2.0.1

  #Page Transitions
  page_transition: ^2.1.0
  intl: ^0.19.0

  #State Management
  flutter_bloc: ^8.0.8

  image_picker: ^1.0.7

  #QR displaying and scanning
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner:
  chopper_generator:

  #Local Storage
  hive_generator:

flutter:
  uses-material-design: true
